config/routes.rb
Rails.application.routes.draw do
  constraints(host: /\Awww\./i) do
    get "(*any)" => redirect { |params, request|
      URI.parse(request.url).tap { |uri| uri.host = uri.host.gsub(/\Awww\./, "") }.to_s
    }
  end

  devise_for :users, controllers: {confirmations: "confirmations"}

  ### USERS ###
  authenticate :user do
    resources :users, only: [] do
      collection do
        get :stop_impersonating
      end
    end
    resources :accounts do
      collection do
        get :current
      end
    end
  end

  ### ADMIN ###
  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      require "sidekiq/web"
      require "sidekiq-scheduler/web"
      mount Sidekiq::Web => "/sidekiq"

      resources :users, except: [:show] do
        member do
          get :impersonate
        end
      end
      resource :dashboard, only: [:show], controller: "dashboard"
    end
  end

  ### DEVELOPER ###
  authenticate :user, lambda { |u| u.developer? } do
    namespace :developer do
      resources :api_tokens
    end
    apipie
  end

  #### API ####
  namespace :api do
    get "status", to: "api#status"
    api_version(
      module: "V1",
      header: {name: "Accept", value: "application/api.rails-starter-7.com; version=1"},
      path: {value: "v1"},
      default: true
    ) do
      resource :auth, only: [:create]
      resource :me, controller: :me
    end
  end

  ### SYSTEM ###
  get "/status", to: "health#status"

  ### PUBLIC ###
  get "/sitemap.xml" => "website/sitemaps#index", :defaults => {format: "xml"}
  get "/robots.txt" => "website/robots#index", :defaults => {format: "text"}
  sitepress_pages root: true, controller: "website/website"
end

app/models/api_token.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: api_tokens
#
#  id         :uuid             not null, primary key
#  calls      :integer          default(0), not null
#  deleted_at :datetime
#  name       :string           not null
#  token      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :uuid             not null
#
# Indexes
#
#  index_api_tokens_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class ApiToken < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :token, presence: true

  scope :active, -> { where(deleted_at: nil) }

  scope :deleted, -> { where.not(deleted: nil) }

  def delete!
    update(deleted_at: Time.current)
  end

  def called!
  end

  def make_token
    self.token = JsonToken.encode({user_id: user_id})
    self
  end

  def to_s
    name
  end
end

app/controllers/developer.rb
# frozen_string_literal: true

module Developer
end

app/controllers/developer/api_tokens_controller.rb
# frozen_string_literal: true

class Developer::ApiTokensController < Developer::DevelopersController
  load_resource

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @api_token = ApiToken.new(api_token_params.merge(user: current_user)).make_token

    if @api_token.save
      redirect_to [:developer, @api_token], notice: "Api token was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @api_token.update(api_token_params)
      redirect_to [:developer, @api_token], notice: "Api token was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @api_token.delete!
    redirect_to developer_api_tokens_url, notice: "Api token was successfully destroyed."
  end

  private

  def api_token_params
    params.require(:api_token).permit(:name)
  end
end

app/controllers/developer/developers_controller.rb
# frozen_string_literal: true

class Developer::DevelopersController < ApplicationController
  # Scope pundit to admin
  def policy_scope(scope, **kwargs)
    super([:developer, scope], **kwargs)
  end

  # Scope pundit to admin
  def authorize(record, query = nil, **kwargs)
    super([:developer, record], query, **kwargs)
  end

  # Scope pundit to admin
  def permitted_attributes(record, action = action_name)
    super([:developer, record], action)
  end
end

app/views/developer/api_tokens/_form.html.slim
= simple_form_for([:developer, @api_token]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/developer/api_tokens/edit.html.slim
h1 Edit API Token

== render 'form'

= link_to 'Show', [:developer, @api_token]
= link_to 'Back', developer_api_tokens_path

app/views/developer/api_tokens/index.html.slim
h1 API Tokens

table
  thead
    tr
      th Name
      th Token
      th User
      th Deleted At
      th Calls

  tbody
    - @api_tokens.each do |api_token|
      tr
        td
          = link_to api_token.name, [:developer, api_token]
          =< link_to edit_developer_api_token_path(api_token) do
            = heroicon "pencil", options: { class: "w-4 h-4" }
          - if api_token.deleted_at.nil?
            =< button_to [:developer, api_token], method: :delete, data: { turbo_confirm: "Delete #{api_token.name} token?", confirm: "Delete #{api_token.name} token?" } do
              = heroicon "trash", options: { class: "w-4 h-4" }
        td = truncate api_token.token
        td = api_token.user || ""
        td = api_token.deleted_at || ""
        td = api_token.calls || ""

= link_to "New API Token", new_developer_api_token_path

app/views/developer/api_tokens/new.html.slim
h1 New API Token

== render 'form'

= link_to 'Back', developer_api_tokens_path

app/views/developer/api_tokens/show.html.slim
h1 API Token

div id="#{dom_id @api_token}"
  p
    strong User:
    =< @api_token.user
  p
    strong Name:
    =< @api_token.name
  p
    strong Token:
    =< @api_token.token
  p
    strong Deleted at:
    =< @api_token.deleted_at
  p
    strong Calls:
    =< @api_token.calls

= link_to "Edit", edit_developer_api_token_path(@api_token)
= link_to "Back", developer_api_tokens_path