config/routes.rb
Rails.application.routes.draw do
  constraints(host: /\Awww\./i) do
    get "(*any)" => redirect { |params, request|
      URI.parse(request.url).tap { |uri| uri.host = uri.host.gsub(/\Awww\./, "") }.to_s
    }
  end

  devise_for :users, controllers: {confirmations: "confirmations"}

  ### USERS ###
  authenticate :user do
    resources :users, only: [] do
      collection do
        get :stop_impersonating
      end
    end
    resources :accounts do
      collection do
        get :current
      end
    end
  end

  ### ADMIN ###
  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      require "sidekiq/web"
      require "sidekiq-scheduler/web"
      mount Sidekiq::Web => "/sidekiq"

      resources :users, except: [:show] do
        member do
          get :impersonate
        end
      end
      resource :dashboard, only: [:show], controller: "dashboard"
    end
  end

  ### DEVELOPER ###
  authenticate :user, lambda { |u| u.developer? } do
    namespace :developer do
      resources :api_tokens
    end
    apipie
  end

  #### API ####
  namespace :api do
    get "status", to: "api#status"
    api_version(
      module: "V1",
      header: {name: "Accept", value: "application/api.rails-starter-7.com; version=1"},
      path: {value: "v1"},
      default: true
    ) do
      resource :auth, only: [:create]
      resource :me, controller: :me
    end
  end

  ### SYSTEM ###
  get "/status", to: "health#status"

  ### PUBLIC ###
  get "/sitemap.xml" => "website/sitemaps#index", :defaults => {format: "xml"}
  get "/robots.txt" => "website/robots#index", :defaults => {format: "text"}
  sitepress_pages root: true, controller: "website/website"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :uuid             not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  failed_attempts        :integer          default(0), not null
#  first_name             :string           not null
#  last_name              :string           not null
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string
#  locked_at              :datetime
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role_mask              :integer          default(0), not null
#  sign_in_count          :integer          default(0), not null
#  unconfirmed_email      :string
#  unlock_token           :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_unlock_token          (unlock_token) UNIQUE
#
class User < ApplicationRecord
  include MaskedAttribute
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable,
    :confirmable, :lockable, :timeoutable, :trackable

  has_many :account_users, dependent: :destroy
  has_many :accounts, through: :account_users
  has_many :api_tokens

  masked_attribute :roles, %i[admin sysadmin developer]

  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def to_s
    "#{first_name} #{last_name} <#{email}>"
  end

  def gravatar_url size = 64, default = "mp"
    email_address = email.downcase
    hash = Digest::MD5.hexdigest(email_address)

    "https://www.gravatar.com/avatar/#{hash}?s=#{size}&d=#{default}"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  load_resource

  def index
  end

  def new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_url, notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    p = user_params
    if @user.update(p)
      redirect_to admin_users_url, notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: "User was successfully destroyed."
  end

  def impersonate
    impersonate_user(@user)
    redirect_to current_accounts_path
  end

  private

  def user_params
    permitted_attributes(User).tap do |user_params|
      if user_params.delete(:confirmed?) == "1" && !@user.confirmed?
        user_params[:confirmed_at] = DateTime.current
      else
        user_params.delete(:confirmed_at)
      end

      if user_params.delete(:locked_at?) == "1"
        user_params[:locked_at] = nil
      else
        user_params.delete(:locked_at)
      end

      if user_params[:password].blank?
        user_params.delete(:password)
      else
        user_params[:password_confirmation] = user_params[:password]
      end

      if user_params[:roles]
        str_roles = User::ROLES.map(&:to_s)
        user_params[:roles] = user_params[:roles].flat_map do |role_str|
          if str_roles.include?(role_str)
            role_str.to_sym
          end
        end.compact
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_scoped_check :stop_impersonating
  load_resource

  def stop_impersonating
    stop_impersonating_user
    redirect_to admin_users_path
  end
end

app/views/admin/users/_form.html.slim
= simple_form_for([:admin, @user]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :first_name
    = f.input :last_name
    = f.input :email
    = f.input :password
    = f.input :confirmed?, as: :boolean, label: "Confirm Now"
    = f.input :locked_at?, as: :boolean, label: "Unlock Now"
    = f.input :roles, as: :check_boxes, collection: User::ROLES.map { [_1.to_s.humanize, _1] }

  .form-actions
    = f.button :submit

app/views/admin/users/_user.html.slim
div id="#{dom_id user}"
  p
    strong First name:
    =< user.first_name
  p
    strong Last name:
    =< user.last_name
  p
    strong Email:
    =< user.email
  p
    strong Password:
    =< user.password

app/views/admin/users/edit.html.slim
h1 Editing user

p
  strong Confirmed at:
  =< @user.confirmed_at&.to_fs(:dt_tz)
p
  strong Locked at:
  =< @user.locked_at&.to_fs(:dt_tz)
p
  strong Failed attempts:
  =< @user.failed_attempts
p
  strong Sign in count:
  =< @user.sign_in_count
p
  strong Current IP:
  =< @user.current_sign_in_ip
p
  strong Current sign in:
  =< @user.current_sign_in_at&.to_fs(:dt_tz)
p
  strong Last IP:
  =< @user.last_sign_in_ip
p
  strong Last sign in:
  =< @user.last_sign_in_at&.to_fs(:dt_tz)
p
  strong Created:
  =< @user.created_at.to_fs(:dt_tz)

== render "form", user: @user

br

div
  =< link_to "Back to users", admin_users_path

app/views/admin/users/index.html.slim
h1 Users

#users
  - @users.each do |user|
    == render user
    p
      = link_to "Edit this user", edit_admin_user_path(user)
      = link_to "Log in as", impersonate_admin_user_path(user)

= link_to "New user", new_admin_user_path

app/views/admin/users/new.html.slim
h1 New user

== render "form", user: @user

br

div
  = link_to "Back to users", admin_users_path