config/routes.rb
Rails.application.routes.draw do
  constraints(host: /\Awww\./i) do
    get "(*any)" => redirect { |params, request|
      URI.parse(request.url).tap { |uri| uri.host = uri.host.gsub(/\Awww\./, "") }.to_s
    }
  end

  devise_for :users, controllers: {confirmations: "confirmations"}

  ### USERS ###
  authenticate :user do
    resources :users, only: [] do
      collection do
        get :stop_impersonating
      end
    end
    resources :accounts do
      collection do
        get :current
      end
    end
  end

  ### ADMIN ###
  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      require "sidekiq/web"
      require "sidekiq-scheduler/web"
      mount Sidekiq::Web => "/sidekiq"

      resources :users, except: [:show] do
        member do
          get :impersonate
        end
      end
      resource :dashboard, only: [:show], controller: "dashboard"
    end
  end

  ### DEVELOPER ###
  authenticate :user, lambda { |u| u.developer? } do
    namespace :developer do
      resources :api_tokens
    end
    apipie
  end

  #### API ####
  namespace :api do
    get "status", to: "api#status"
    api_version(
      module: "V1",
      header: {name: "Accept", value: "application/api.rails-starter-7.com; version=1"},
      path: {value: "v1"},
      default: true
    ) do
      resource :auth, only: [:create]
      resource :me, controller: :me
    end
  end

  ### SYSTEM ###
  get "/status", to: "health#status"

  ### PUBLIC ###
  get "/sitemap.xml" => "website/sitemaps#index", :defaults => {format: "xml"}
  get "/robots.txt" => "website/robots#index", :defaults => {format: "text"}
  sitepress_pages root: true, controller: "website/website"
end

app/views/layouts/_head.html.slim
meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
meta charset="utf-8"
meta content="IE=edge" http-equiv="X-UA-Compatible"
meta content="width=device-width, initial-scale=1" name="viewport"

title
  - if Rails.env.development?
    | DEV -
  - if content_for(:title)
    =< yield :title
  - else
    =< "Rails Starter 7"

= csrf_meta_tags
= csp_meta_tag

= display_meta_tags site: "Rails Starter 7",
  reverse: true,
  description: "Rails starter kit, get moving quickly!",
  image_src: image_url("rails-7-starter.png"),
  og: { title: :title,
    description: :description,
    site_name: :site,
    url: :canonical,
    image: :image_src,
    type: "website",
  },
  twitter: { card: "summary", site: "@candland" }

link rel="icon" type="image/x-icon" href="/favicon.ico"
link rel="icon" type="image/png" href="/favicon.png" sizes="32x32"
link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"
meta name="msapplication-TileImage" content="/mstile-144x144.png"
meta name="msapplication-TileColor" content="#ffffff"

= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"

= stylesheet_link_tag "application", "data-turbo-track": "reload"
= javascript_importmap_tags

= yield :js_head

app/views/layouts/_navigation.html.slim
nav.flex.flex-row.justify-between.px-3.py-3.border-b.border-black.mb-6
  header.flex.flex-row.gap-3.items-center
    h2.text-lg.font-medium
      = link_to "RailsStarter7", "/"
    - if signed_in? && Current.account
      h3 = Current.account

  #menu.flex.gap-4.items-center
    .hidden.md:flex.gap-4.items-center
      - if signed_in?
        = link_to accounts_path, class: "flex items-center gap-1" do
          => heroicon("arrow-path", options: { class: "h-4 w-4" })
          | Change Account
      - else
        = link_to new_user_session_path, class: "flex items-center gap-1" do
          => heroicon("arrow-right-on-rectangle", options: { class: "h-4 w-4" })
          | Log in

        = link_to new_user_registration_path, class: "flex items-center gap-1" do
          => heroicon("user-plus", options: { class: "h-4 w-4" })
          | Sign up

    .relative data-controller="dropdown"
      - if signed_in?
        => link_to "#", class: "flex items-center gap-1", data: { action: "click->dropdown#show" } do
          img.inline-block.h-9.w-9.rounded-full alt="" src="#{current_user.gravatar_url}"
          span.flex.place-items-center = Current.user.first_name

      - else
        => link_to "#", class: "flex md:hidden items-center gap-1", data: { action: "click->dropdown#show" } do
          => heroicon("bars-3", options: { class: "h-4 w-4" })
        / Mobile thing

      #user_menu.hidden.absolute.bg-white.p-4.shadow.border.right-0.w-48.flex.flex-col.gap-4 data-dropdown-target="submenu"
        - if signed_in?
          = link_to edit_user_registration_path, class: "flex items-center gap-1" do
              => heroicon("pencil", options: { class: "h-4 w-4" })
              | Profile

          / Mobile Items
          = link_to accounts_path, class: "flex md:hidden items-center gap-1" do
            => heroicon("arrow-path", options: { class: "h-4 w-4" })
            | Change Account

          / Drop down items
          - if policy([:admin, :dashboard]).show?
            = link_to admin_dashboard_path, class: "flex items-center gap-1" do
              => heroicon("lock-closed", options: { class: "h-4 w-4" })
              | Admin

          - if policy([:developer, :api_token]).index?
            = link_to developer_api_tokens_path, class: "flex items-center gap-1" do
              => heroicon("code-bracket", options: { class: "h-4 w-4" })
              | API Tokens

          - if policy([:developer]).docs?
            = link_to "/developer/apipie", class: "flex items-center gap-1", target: "_blank" do
              => heroicon("document", options: { class: "h-4 w-4" })
              | API Docs

          = link_to destroy_user_session_path, class: "flex items-center gap-1" do
            => heroicon("arrow-left-on-rectangle", options: { class: "h-4 w-4" })
            | Log out

        - else
          = link_to new_user_session_path, class: "flex md:hidden items-center gap-1" do
            => heroicon("arrow-right-on-rectangle", options: { class: "h-4 w-4" })
            | Log in

          = link_to new_user_registration_path, class: "flex md:hidden items-center gap-1" do
            => heroicon("user-plus", options: { class: "h-4 w-4" })
            | Sign up

app/views/layouts/admin.html.slim
- content_for :banner do
  .bg-green-600.text-white.text-right.px-3.text-medium
    | Admin

- content_for :content do
  = yield

= render template: "layouts/application"

app/views/layouts/application.html.slim
doctype html
html class="h-full antialiased" lang="#{I18n.locale}"
  head
    = render "layouts/head"
  body.h-screen.flex.flex-col.bg-white
    = render partial: "shared/flash"
    - if signed_in? && current_user != true_user
      .bg-red-600.text-white.text-center
        | You (#{true_user.first_name}) are signed in as #{current_user.to_s}
        =< link_to "Back to admin", stop_impersonating_users_path

    - if content_for?(:banner)
      = yield(:banner)

    = render "layouts/navigation"

    .container.mx-auto.px-6
      = content_for?(:content) ? yield(:content) : yield

app/views/layouts/application.turbo_stream.slim
= turbo_stream.append "flash" do
  = render "shared/flashes"
= yield

app/views/layouts/devise.html.slim
- content_for :content do
  .max-w-lg.mx-auto
    = yield

= render template: "layouts/application"

app/views/layouts/website.html.slim
- set_meta_tags to_meta_tags(current_page)

- content_for :content do
  - current_page.parents.any?
    menu.flex.flex-row.gap-3.text-sm.text-gray-700.mb-4
      - current_page.parents.reverse.each_with_index do |parent, idx|
        li
          a href=parent.request_path = parent.data.title
        - if idx < current_page.parents.size - 1
          li \

  = yield

= render template: "layouts/application"