config/routes.rb
Rails.application.routes.draw do
  constraints(host: /\Awww\./i) do
    get "(*any)" => redirect { |params, request|
      URI.parse(request.url).tap { |uri| uri.host = uri.host.gsub(/\Awww\./, "") }.to_s
    }
  end

  devise_for :users, controllers: {confirmations: "confirmations"}

  ### USERS ###
  authenticate :user do
    resources :users, only: [] do
      collection do
        get :stop_impersonating
      end
    end
    resources :accounts do
      collection do
        get :current
      end
    end
  end

  ### ADMIN ###
  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      require "sidekiq/web"
      require "sidekiq-scheduler/web"
      mount Sidekiq::Web => "/sidekiq"

      resources :users, except: [:show] do
        member do
          get :impersonate
        end
      end
      resource :dashboard, only: [:show], controller: "dashboard"
    end
  end

  ### DEVELOPER ###
  authenticate :user, lambda { |u| u.developer? } do
    namespace :developer do
      resources :api_tokens
    end
    apipie
  end

  #### API ####
  namespace :api do
    get "status", to: "api#status"
    api_version(
      module: "V1",
      header: {name: "Accept", value: "application/api.rails-starter-7.com; version=1"},
      path: {value: "v1"},
      default: true
    ) do
      resource :auth, only: [:create]
      resource :me, controller: :me
    end
  end

  ### SYSTEM ###
  get "/status", to: "health#status"

  ### PUBLIC ###
  get "/sitemap.xml" => "website/sitemaps#index", :defaults => {format: "xml"}
  get "/robots.txt" => "website/robots#index", :defaults => {format: "text"}
  sitepress_pages root: true, controller: "website/website"
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id         :uuid             not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Account < ApplicationRecord
  has_many :account_users, dependent: :destroy
  has_many :users, through: :account_users

  validates :name, presence: true

  def to_s
    name
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  load_resource

  def index
    @pagy, @accounts = pagy(@accounts)
  end

  def show
    set_current_account @account
    Current.account = @account
  end

  def current
    @account = Current.account
    if @account
      authorize @account, :show?
      render :show
    else
      redirect_to new_account_path
    end
  end

  def new
  end

  def edit
  end

  def create
    @account = Account.new(account_params)
    @account.users << current_user

    if @account.save
      set_current_account @account
      redirect_to @account, notice: "Account was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @account.update(account_params)
      redirect_to @account, notice: "Account was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @account.destroy
    redirect_to accounts_url, notice: "Account was successfully destroyed."
  end

  private

  def account_params
    permitted_attributes(Account)
  end
end

app/views/accounts/_account.html.slim
div id="#{dom_id account}"
  p
    strong Name:
    =< account.name

app/views/accounts/_form.html.slim
= simple_form_for(@account) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .fields
    = f.input :name

  .actions
    = f.submit

app/views/accounts/edit.html.slim
h1 Editing account

== render "form", account: @account

br

div
  => link_to "Show this account", @account
  '|
  =< link_to "Back to accounts", accounts_path

app/views/accounts/index.html.slim
h1 Accounts

#accounts
  - @accounts.each do |account|
    == render account
    p
      = link_to "Show this account", account

= link_to "New account", new_account_path

== pagy_nav(@pagy)

app/views/accounts/new.html.slim
h1 New account

== render "form", account: @account

br

div
  = link_to "Back to accounts", accounts_path

app/views/accounts/show.html.slim
= component :card do
  == render @account

div
  => link_to "Edit this account", edit_account_path(@account)
  '|
  =< link_to "Back to accounts", accounts_path

  = button_to "Destroy this account", @account, method: :delete, data: { turbo_confirm: "Are you sure?" }